# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cpu_mem_stat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot as Slot, QThread, pyqtSignal as Signal

import sys
import os

path = os.path.dirname(os.path.abspath(sys.argv[0]))
file = open(f"{path}/temp/temp_pod_stat", "r")
cmd = file.read().split("#")
file.close()
pod = cmd[1]
cmd = cmd[0]


class Worker(QObject):
    cpu_stat = Signal(str)
    ram_stat = Signal(str)
    running = Signal()

    @Slot()
    def callProgram(self):
        import os

        while True:
            try:

                out = os.popen(cmd).readlines()
                temp = out[1].split(" ")
                tempx = []
                for i in temp:
                    if i.isalnum():
                        strx = ""
                        for j in i:
                            if j.isdigit():
                                strx += j
                        tempx.append(strx)
                cpu = tempx[0]
                ram = tempx[1]

                self.cpu_stat.emit(str(cpu))
                self.ram_stat.emit(str(ram))

            except Exception:
                pass


class Ui_MainWindow(object):

    def update_cpu_stat(self, v):
        self.cpu_disp.display(v)

    def update_ram_stat(self, v):
        self.ram_disp.display(v)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 209)
        MainWindow.setStyleSheet("background-color: rgb(1,1,1);\n"
                                 "color: rgb(198, 70, 0);\n"
                                 "font: 11pt \"Ubuntu\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.cpu_disp = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_disp.sizePolicy().hasHeightForWidth())
        self.cpu_disp.setSizePolicy(sizePolicy)
        self.cpu_disp.setStyleSheet("font: 14pt ;\n"
                                    "background-color: rgb(14, 14, 2);\n"
                                    "selection-background-color: rgb(206, 92, 0);\n"
                                    "selection-color: rgb(0, 0, 0);\n"
                                    "border: 1px solid rgb(165, 29, 45)\n"
                                    "")
        self.cpu_disp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpu_disp.setSmallDecimalPoint(False)
        self.cpu_disp.setDigitCount(5)
        self.cpu_disp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.cpu_disp.setProperty("value", 0.0)
        self.cpu_disp.setProperty("intValue", 0)
        self.cpu_disp.setObjectName("cpu_disp")
        self.horizontalLayout.addWidget(self.cpu_disp)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.ram_disp = QtWidgets.QLCDNumber(self.centralwidget)
        self.ram_disp.setStyleSheet("font: 14pt ;\n"
                                    "background-color: rgb(14, 14, 2);\n"
                                    "selection-background-color: rgb(206, 92, 0);\n"
                                    "selection-color: rgb(0, 0, 0);\n"
                                    "border: 1px solid rgb(165, 29, 45)\n"
                                    "")
        self.ram_disp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ram_disp.setSmallDecimalPoint(False)
        self.ram_disp.setDigitCount(5)
        self.ram_disp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.ram_disp.setProperty("value", 0.0)
        self.ram_disp.setProperty("intValue", 0)
        self.ram_disp.setObjectName("ram_disp")
        self.horizontalLayout.addWidget(self.ram_disp)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.work_requested = Signal(int)
        self.worker = Worker()
        self.worker_thread = QThread()

        self.worker_thread.started.connect(self.worker.callProgram)
        self.worker.cpu_stat.connect(self.update_cpu_stat)
        self.worker.ram_stat.connect(self.update_ram_stat)
        self.worker.moveToThread(self.worker_thread)
        self.worker_thread.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow",f"Pod ({pod}) Resource Status"))
        self.label_8.setText(_translate("MainWindow", "CPU"))
        self.label_10.setText(_translate("MainWindow", "m"))
        self.label_9.setText(_translate("MainWindow", "RAM"))
        self.label_11.setText(_translate("MainWindow", "Mi"))


def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(w)
    w.show()
    sys.exit(app.exec_())


main()
