# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cpu_mem_stat_node.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot as Slot, QThread, pyqtSignal as Signal
import sys
import os

path = os.path.dirname(os.path.abspath(sys.argv[0]))
file = open(f"{path}/temp/temp_node_stat", "r")
cmd = file.read().split("#")
file.close()
node = cmd[1]
cmd = cmd[0]
class Worker(QObject):
    cpu_core = Signal(str)
    cpu_per=Signal(str)
    ram_usage = Signal(str)
    ram_per=Signal(str)
    running = Signal()

    @Slot()
    def callProgram(self):
        import os

        while True:
            try:

                out = os.popen(cmd).readlines()

                temp = out[1].split(" ")
                tempx = []

                for i in temp:
                    if i.isalnum() or "%" in i:

                        strx = ""
                        for j in i:
                            if j.isdigit():
                                strx += j
                        tempx.append(strx)

                cpu_core = tempx[0]
                cpu_per=tempx[1]
                ram_usage=tempx[2]
                ram_per = tempx[3]

                self.cpu_core.emit(str(cpu_core))
                self.cpu_per.emit(str(cpu_per))
                self.ram_usage.emit(str(ram_usage))
                self.ram_per.emit(str(ram_per))


            except Exception:
                pass


class Ui_MainWindow(object):
    def update_cpu_core_stat(self, v):
        self.cpu_disp.display(v)

    def update_ram_usage_stat(self, v):
        self.ram_disp.display(v)
    def update_cpu_per_stat(self, v):
        self.cpu_per.display(v)
        self.cpu_bar.setValue(int(v))

    def update_ram_per_stat(self, v):
        self.ram_per.display(v)
        self.ram_bar.setValue(int(v))
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 233)
        MainWindow.setStyleSheet("background-color: rgb(1,1,1);\n"
"color: rgb(198, 70, 0);\n"
"font: 11pt \"Ubuntu\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cpu_bar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_bar.sizePolicy().hasHeightForWidth())
        self.cpu_bar.setSizePolicy(sizePolicy)
        self.cpu_bar.setMinimumSize(QtCore.QSize(0, 0))
        self.cpu_bar.setStyleSheet("font: 14pt ;\n"
"selection-background-color: rgb(165, 29, 45);\n"
"\n"
"\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.cpu_bar.setProperty("value", 0)
        self.cpu_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_bar.setTextVisible(False)
        self.cpu_bar.setOrientation(QtCore.Qt.Vertical)
        self.cpu_bar.setObjectName("cpu_bar")
        self.horizontalLayout_2.addWidget(self.cpu_bar)
        self.cpu_per = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_per.sizePolicy().hasHeightForWidth())
        self.cpu_per.setSizePolicy(sizePolicy)
        self.cpu_per.setMinimumSize(QtCore.QSize(220, 0))
        self.cpu_per.setStyleSheet("font: 14pt ;\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.cpu_per.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpu_per.setSmallDecimalPoint(False)
        self.cpu_per.setDigitCount(6)
        self.cpu_per.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.cpu_per.setProperty("value", 0.0)
        self.cpu_per.setProperty("intValue", 0)
        self.cpu_per.setObjectName("cpu_per")
        self.horizontalLayout_2.addWidget(self.cpu_per)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        spacerItem1 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.ram_bar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ram_bar.sizePolicy().hasHeightForWidth())
        self.ram_bar.setSizePolicy(sizePolicy)
        self.ram_bar.setStyleSheet("font: 14pt ;\n"
"selection-background-color: rgb(165, 29, 45);\n"
"\n"
"\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.ram_bar.setProperty("value", 0)
        self.ram_bar.setTextVisible(False)
        self.ram_bar.setOrientation(QtCore.Qt.Vertical)
        self.ram_bar.setObjectName("ram_bar")
        self.horizontalLayout_2.addWidget(self.ram_bar)
        self.ram_per = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ram_per.sizePolicy().hasHeightForWidth())
        self.ram_per.setSizePolicy(sizePolicy)
        self.ram_per.setStyleSheet("font: 14pt ;\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.ram_per.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ram_per.setSmallDecimalPoint(False)
        self.ram_per.setDigitCount(6)
        self.ram_per.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.ram_per.setProperty("value", 0.0)
        self.ram_per.setProperty("intValue", 0)
        self.ram_per.setObjectName("ram_per")
        self.horizontalLayout_2.addWidget(self.ram_per)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.cpu_disp = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_disp.sizePolicy().hasHeightForWidth())
        self.cpu_disp.setSizePolicy(sizePolicy)
        self.cpu_disp.setStyleSheet("font: 14pt ;\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.cpu_disp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpu_disp.setSmallDecimalPoint(False)
        self.cpu_disp.setDigitCount(6)
        self.cpu_disp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.cpu_disp.setProperty("value", 0.0)
        self.cpu_disp.setProperty("intValue", 0)
        self.cpu_disp.setObjectName("cpu_disp")
        self.horizontalLayout.addWidget(self.cpu_disp)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.ram_disp = QtWidgets.QLCDNumber(self.centralwidget)
        self.ram_disp.setStyleSheet("font: 14pt ;\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.ram_disp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ram_disp.setSmallDecimalPoint(False)
        self.ram_disp.setDigitCount(6)
        self.ram_disp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.ram_disp.setProperty("value", 0.0)
        self.ram_disp.setProperty("intValue", 0)
        self.ram_disp.setObjectName("ram_disp")
        self.horizontalLayout.addWidget(self.ram_disp)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet("font: 75 36pt \"Umpush\";")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        spacerItem3 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.work_requested = Signal(int)
        self.worker = Worker()
        self.worker_thread = QThread()

        self.worker_thread.started.connect(self.worker.callProgram)
        self.worker.cpu_core.connect(self.update_cpu_core_stat)
        self.worker.ram_usage.connect(self.update_ram_usage_stat)
        self.worker.cpu_per.connect(self.update_cpu_per_stat)
        self.worker.ram_per.connect(self.update_ram_per_stat)
        self.worker.moveToThread(self.worker_thread)
        self.worker_thread.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"Node resource ({node})"))
        self.label_12.setText(_translate("MainWindow", "%"))
        self.label_13.setText(_translate("MainWindow", "%"))
        self.label_8.setText(_translate("MainWindow", "CPU"))
        self.label_10.setText(_translate("MainWindow", "m"))
        self.label_9.setText(_translate("MainWindow", "RAM"))
        self.label_11.setText(_translate("MainWindow", "Mi"))
def main():
 import sys
 app = QtWidgets.QApplication(sys.argv)
 w = QtWidgets.QMainWindow()
 ui = Ui_MainWindow()
 ui.setupUi(w)
 w.show()
 sys.exit(app.exec_())
main()