# -*- coding: utf-8 -*-
import os
import time

# Form implementation generated from reading ui file 'edit_disp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import json
import yaml
import sys
import os

path = os.path.dirname(os.path.abspath(sys.argv[0]))

file = open(f"{path}/temp/temp_buff_pv_edit_cmd", "r")
res=file.read().split("#")
file.close()
cmd=res[0]
pv=res[1]
password=res[2]
user=res[3]
ip=res[4]




class Ui_MainWindow(object):
    def dataReady(self):
        cursor = self.disp.textCursor()
        cursor.movePosition(cursor.End)

        cursor.insertText(
            str(self.process.readAll().data().decode()))

    def callProgram(self):

        self.process.start("/bin/bash", ["-c",f"{cmd}"])

    def save_pvc(self):
        self.process.close()
        text = self.disp.toPlainText()
        file = open('temp_pv.yaml', 'w')
        file.write(text)
        file.close()
        file = open('temp_pv.yaml', 'r')
        yaml_data = yaml.safe_load(file)
        file.close()
        del yaml_data["status"]
        file = open('temp_pv.json', 'w')
        json.dump(yaml_data,file,indent=6)
        file.close()
        time.sleep(1)
        self.process_edit_pv_consent = QtCore.QProcess()
        self.process_edit_pv_consent.start('python3', ['-u', f'{path}/edit_pv_consent.py'])
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 810)
        MainWindow.setStyleSheet("background-color: rgb(1,1,1);\n"
"color: rgb(198, 70, 0);\n"
"font: 11pt \"Ubuntu\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.disp = QtWidgets.QTextBrowser(self.centralwidget)
        self.disp.setStyleSheet("font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(38, 162, 105);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(198, 70, 0)\n"
"")
        self.disp.setFrameShape(QtWidgets.QFrame.Box)
        self.disp.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.disp.setReadOnly(False)
        self.disp.setObjectName("disp")
        self.verticalLayout.addWidget(self.disp)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_edit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_edit.sizePolicy().hasHeightForWidth())
        self.save_edit.setSizePolicy(sizePolicy)
        self.save_edit.setMinimumSize(QtCore.QSize(200, 50))
        self.save_edit.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.save_edit.setFlat(True)
        self.save_edit.setObjectName("save_edit")
        self.horizontalLayout.addWidget(self.save_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.process=QtCore.QProcess()
        self.process.readyRead.connect(self.dataReady)
        self.callProgram()
        self.save_edit.clicked.connect(lambda : self.save_pvc())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"PV ({pv})"))
        self.save_edit.setText(_translate("MainWindow", "UPDATE"))
def main():
 import sys
 app = QtWidgets.QApplication(sys.argv)
 w = QtWidgets.QMainWindow()
 ui = Ui_MainWindow()
 ui.setupUi(w)
 w.show()
 sys.exit(app.exec_())
main()