# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dev_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# Author: Sourish Datta
# Email: sourishonax@gmail.com
# Phone: (+91) 8343003660


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os

path = os.path.dirname(os.path.abspath(sys.argv[0]))

class Ui_MainWindow(object):
    def add_ssh(self):
        ip = self.ssh_ip.text()
        name = self.ssh_alias.text()
        password = self.ssh_pass.text()
        if ip and name and password:
            import json
            file = open(f'{path}/temp/ssh.json', 'r')
            data = json.load(file)
            file.close()
            data[name] = [ip, password]
            file = open(f'{path}/temp/ssh.json', 'w')
            json.dump(data, file)
            file.close()
            self.ssh_combo.clear()
            for i in data.keys():
                if i != "Choose":
                    self.ssh_combo.addItem(i+" "+data[i][0])
            self.ssh_status.setText(f"Server {ip} has added.")

        else:
            self.ssh_status.setText("Incorrect Info")
    def ssh_combo_clear(self):
        self.ssh_combo.clear()
    def remove_ssh(self):
        import json
        file = open(f'{path}/temp/ssh.json', 'r')
        data = json.load(file)
        file.close()
        remove_server=self.ssh_combo.currentText().split(" ")
        del data[remove_server[0]]
        file = open(f'{path}/temp/ssh.json', 'w')
        json.dump(data, file)
        file.close()
        self.ssh_combo.clear()
        for i in data.keys():
            if i!="Choose":
                self.ssh_combo.addItem(i + " " + data[i][0])
        self.ssh_status.setText(f"Server {remove_server} has removed.")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 441)
        MainWindow.setStyleSheet("background-color: rgb(1,1,1);\n"
"color: rgb(198, 70, 0);\n"
"font: 11pt \"Ubuntu\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ssh_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.ssh_ip.setGeometry(QtCore.QRect(40, 80, 241, 41))
        self.ssh_ip.setStyleSheet("\n"
"font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(38, 162, 105);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.ssh_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.ssh_ip.setObjectName("ssh_ip")
        self.ssh_alias = QtWidgets.QLineEdit(self.centralwidget)
        self.ssh_alias.setGeometry(QtCore.QRect(40, 130, 241, 41))
        self.ssh_alias.setStyleSheet("\n"
"font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(38, 162, 105);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.ssh_alias.setAlignment(QtCore.Qt.AlignCenter)
        self.ssh_alias.setObjectName("ssh_alias")
        self.ssh_add = QtWidgets.QPushButton(self.centralwidget)
        self.ssh_add.setGeometry(QtCore.QRect(320, 130, 151, 41))
        self.ssh_add.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.ssh_add.setFlat(True)
        self.ssh_add.setObjectName("ssh_add")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 40, 281, 17))
        self.label_8.setObjectName("label_8")
        self.ssh_status = QtWidgets.QLabel(self.centralwidget)
        self.ssh_status.setGeometry(QtCore.QRect(10, 380, 481, 51))
        self.ssh_status.setStyleSheet("font: 13pt \"Ubuntu Mono\";\n"
"color: rgb(229, 165, 10);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.ssh_status.setText("")
        self.ssh_status.setObjectName("ssh_status")
        self.ssh_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.ssh_pass.setGeometry(QtCore.QRect(40, 180, 241, 41))
        self.ssh_pass.setStyleSheet("\n"
"font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(38, 162, 105);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)\n"
"")
        self.ssh_pass.setAlignment(QtCore.Qt.AlignCenter)
        self.ssh_pass.setObjectName("ssh_pass")
        self.ssh_combo = QtWidgets.QComboBox(self.centralwidget)
        self.ssh_combo.setGeometry(QtCore.QRect(40, 290, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssh_combo.sizePolicy().hasHeightForWidth())
        self.ssh_combo.setSizePolicy(sizePolicy)
        self.ssh_combo.setStyleSheet("font: 12pt \"Ubuntu Mono\";\n"
"color: rgb(46, 194, 126);\n"
"background-color: rgb(14, 14, 2);\n"
"selection-background-color: rgb(206, 92, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(165, 29, 45)")
        self.ssh_combo.setEditable(False)
        self.ssh_combo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.ssh_combo.setObjectName("ssh_combo")
        self.remove = QtWidgets.QPushButton(self.centralwidget)
        self.remove.setGeometry(QtCore.QRect(320, 290, 151, 41))
        self.remove.setStyleSheet("border: 1px solid rgb(165, 29, 45)")
        self.remove.setFlat(True)
        self.remove.setObjectName("remove")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 250, 281, 17))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        import json
        file = open(f'{path}/temp/ssh.json', 'r')
        data = json.load(file)
        file.close()
        for i in data.keys():
            if i!="Choose":
                self.ssh_combo.addItem(i + " " + data[i][0])
        self.ssh_add.clicked.connect(lambda: self.add_ssh())
        self.remove.clicked.connect(lambda : self.remove_ssh())
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Settings"))
        self.ssh_ip.setPlaceholderText(_translate("MainWindow", "Server-IP"))
        self.ssh_alias.setPlaceholderText(_translate("MainWindow", "Server-NAME"))
        self.ssh_add.setText(_translate("MainWindow", "ADD"))
        self.label_8.setText(_translate("MainWindow", "Add Remote SSH Server"))
        self.ssh_pass.setPlaceholderText(_translate("MainWindow", "Server-PASSWORD"))
        self.remove.setText(_translate("MainWindow", "Remove"))
        self.label_9.setText(_translate("MainWindow", "Remove Remote SSH Server"))
def main():
 import sys
 app = QtWidgets.QApplication(sys.argv)
 w = QtWidgets.QMainWindow()
 ui = Ui_MainWindow()
 ui.setupUi(w)
 w.show()
 sys.exit(app.exec_())
main()